

AI_ORCHESTRATION_PORT = 8000
AI_LLM_WRAPPER_PORT = 8002
OLLAMA_BASE_URL = "http://localhost:11434"

CHAT_BACKEND_URL = "http://localhost"

AI_BRAIN_PORT = 8000
AI_BRAINS_DIRECTORY = 'data/brains'
AI_BRAIN_COLLECTION_NAME = 'COLLECTIoN_NAME'

DATA_DIRECTORY = 'data'