
AI_ORCHESTRATION_PORT = 8003
AI_LLM_WRAPPER_PORT = 8002
AI_BRAIN_PORT = 8001

OLLAMA_BASE_URL = "http://localhost:11434"

CHAT_BACKEND_URL = "http://localhost"

AI_BRAINS_DIRECTORY = 'data/brains'
AI_BRAIN_COLLECTION_NAME = 'COLLECTION_NAME'

DATA_DIRECTORY = '../data/berlin'


